# Generated by Django 5.1.1 on 2024-09-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehiclestatusindividual'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('default_city', models.CharField(max_length=100)),
                ('default_area', models.CharField(max_length=100)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('rented_by_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('rent_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_rented_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('last_rent_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('time_remaining', models.DurationField(blank=True, null=True)),
                ('panic_button_status', models.BooleanField(default=False)),
                ('battery_charge_status', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('contact_support_person', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_message', models.TextField(blank=True, null=True)),
                ('is_out_of_service', models.BooleanField(default=False)),
                ('ticket_number', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='main.fleetowner')),
            ],
        ),
    ]
